#!/bin/bash

install_configs() {
	sudo cp -r .sysconf/* /
	rm -rf .sysconf
	cp -r .[^.]* ~
	mv ~/.git ~/.dotfiles
	echo 'Configs installed'
}

install_touchpad_rules() {
	FILE='/etc/udev/rules.d/01-touchpad.rules'

	sudo sed -i "s/user/$USER/g" $FILE
	sudo sed -i "s|address|$DBUS_SESSION_BUS_ADDRESS|g" $FILE # Error: DBUS_SESSION_BUS_ADDRESS is empty when running in chroot
	echo 'Touchpad udev rules configured'
}

change_acpi_events() {
	FILE='/etc/systemd/logind.conf'


	# Set power key to suspend
	sudo sed -i '/^#HandlePowerKey=/s/poweroff/suspend/g' $FILE
	sudo sed -i '/^#HandlePowerKey=/s/^#//g' $FILE

	echo "ACPI suspend set"
}

config_pacman() {
	FILE='/etc/pacman.conf'

	sudo sed -i '/^#\[multilib\]/,/^#Include/s/#//' $FILE
	echo 'Multilib enabled'

	sudo sed -i '/^#Color/s/#//g' $FILE
	echo 'Pacman color enabled'
}

disable_debug_option_makepkg() {
	sudo sed -i '/^OPTIONS/s/ debug/ !debug/' /etc/makepkg.conf
	echo 'Debug option makepkg disabled'
}

enable_zram() {
	sudo pacman -Sy --needed zram-generator
	sudo systemctl daemon-reload
	sudo systemctl start systemd-zram-setup@zram0.service
	echo 'Zram enabled'
}

install_configs
install_touchpad_rules
change_acpi_events
config_pacman
disable_debug_option_makepkg
enable_zram
