#!/bin/bash

install_configs() {
	sudo cp -r .sysconf/* /
	rm -rf .sysconf
	cp -r .[^.]* ~
	mv ~/.git ~/.dotfiles
	echo 'Configs installed'
}

install_touchpad_rules() {
	FILE='/etc/udev/rules.d/01-touchpad.rules'

	echo "Modifying $FILE"
	sudo sed -i "s/user/$USER/g" $FILE
	sudo sed -i "s|address|$DBUS_SESSION_BUS_ADDRESS|g" $FILE # Error: DBUS_SESSION_BUS_ADDRESS is empty when running in chroot
}

change_acpi_events() {
	FILE='/etc/systemd/logind.conf'

	echo "Modifying $FILE"

	# Suspend when power key is pressed
	sudo sed -i '/^#HandlePowerKey=/s/^#//g' \
		-e '/^HandlePowerKey=/s/poweroff/suspend/g' $FILE
}

config_pacman() {
	FILE='/etc/pacman.conf'

	sudo sed -i '/^#\[multilib\]/,/^#Include/s/#//' $FILE
	echo 'Multilib enabled'

	sudo sed -i '/^#Color/s/#//g' $FILE
	echo 'Pacman color enabled'
}

enable_zram() {
	sudo pacman -S --needed zram-generator
	sudo systemctl daemon-reload
	sudo systemctl start systemd-zram-setup@zram0.service
	echo 'Zram enabled'
}

install_configs

install_touchpad_rules
change_acpi_events
config_pacman

enable_zram
