#!/bin/bash

touchpad() {
    awesome-client "awesome.emit_signal(\"modules::touchpad\", \"$1\")"
}

# Control the touchpad through awesomeWM's signal
# @param: {string} $1 - Value can be 'enable', 'disable' or 'toggle'

touchpad $1 &
