#!/bin/bash

fg=e9cdd0ff
highlight=78dbfb
wrong=cea3ffff
verify=$highlight
transparent=00000000

i3lock --nofork \
    --ignore-empty-password \
    --pass-media-keys \
    --pass-screen-keys \
    --pass-volume-keys \
    \
	--fill \
    --image=/home/meo/pics/wallpapers/wallhaven-m95v79.png \
	\
    --indicator \
    --radius=30 \
    --ring-width=10 \
    --ring-color=$fg \
    --inside-color=$transparent \
    --ringver-color=$highlight \
    --insidever-color=$transparent \
    --ringwrong-color=$wrong \
    --insidewrong-color=$transparent \
    --line-uses-inside \
    --keyhl-color=$highlight \
    --bshl-color=$highlight \
    --separator-color=$highlight \
    --ind-pos="550:500" \
	\
    --force-clock \
    --time-color=$fg \
    --time-str="%I:%M %p" \
    --time-font="Calvin and Hobbes" \
    --time-size=150 \
    --time-pos="ix:iy-300" \
	\
    --date-color=$fg \
    --date-str="%A, %d %B" \
    --date-font="Calvin and Hobbes" \
    --date-size=90 \
    --date-pos="tx:ty+120" \
    \
	--verif-color=$fg \
    --verif-font="Calvin and Hobbes" \
    --verif-size=70 \
    --verif-text="Chotto a minute!" \
    --verif-pos="ix:iy+200" \
	\
	--wrong-color=$fg \
    --wrong-font="Calvin and Hobbes" \
    --wrong-size=70 \
    --wrong-text="Wrong bro!" \
    --wrong-pos="ix:iy+200" \
	\
    --noinput-text=""
